### ISSUE TITLE
Please distribute minified scripts

### ISSUE THREAD

**Issue by uhidontkno** [MercuryWorkshop/bare-mux#2]
Exactly what the title says. Please distribute minified scripts, as it improves performance, boosts Lighthouse scores, and minimizes network bytes transferred.

**Comment by uhidontkno** [comment]
Pull request #3 resolves this issue.

**Comment by velzie** [comment]
do it yourself

**Comment by uhidontkno** [comment]
> do it yourself

This should be done by default.

**Comment by Percslol** [comment]
fixed in commit (c299c00a36e5d6052dee0cedc75a34c69c5bf795)

**Comment by uhidontkno** [comment]
Not sure why @velzie decided to be ignorant about it
